<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Water Quality Dashboard (PHP Version)</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    
    <!-- Link to external CSS file -->
    <link rel="stylesheet" href="assets/style.css">
</head>
<body class="bg-black text-white">
    
    <!-- Main Navigation -->
    <nav class="bg-gray-900 p-4 shadow-lg sticky top-0 z-40">
        <div class="flex justify-center items-center gap-2 sm:gap-4">
            <button data-view="dashboard" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base active">Dashboard</button>
            <button data-view="graph" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Graph</button>
            <button data-view="status" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Device Status</button>
            <button data-view="settings" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Settings</button>
        </div>
    </nav>

    <!-- Dashboard View - Full Screen -->
    <div id="view-dashboard" class="view active dashboard-background">
        <div class="dashboard-overlay"></div>
        <div class="dashboard-content">
            <div id="dashboard-ui-elements">
                <header id="dashboard-header" style="background-size: cover; background-position: center;">
                    <div class="flex items-center gap-4">
                        <img id="dashboard-logo" src="https://placehold.co/200x200/transparent/white?text=Logo" alt="Logo" class="object-contain">
                        <div>
                            <h2 id="header-caption" class="font-bold text-white"></h2>
                            <p id="header-subcaption" class="text-gray-300"></p>
                        </div>
                    </div>
                </header>
                
                <div id="operation-mode-lights" class="flex justify-center items-center gap-4">
                    <!-- Operation mode lights will be generated by JS -->
                </div>
            </div>
            
            <!-- Main Dashboard Content -->
            <div id="dashboard-graph-content" class="dashboard-main-content active">
                <!-- Chart Container -->
                <div id="dashboard-chart-container">
                    <canvas id="dashboardBarChart"></canvas>
                </div>
                
                <!-- Values Container -->
                <div id="dashboard-values-container">
                    <!-- Values will be generated by JS -->
                </div>
            </div>
            
            <!-- Video Content -->
            <div id="dashboard-video-content" class="dashboard-main-content">
                <video id="dashboard-video" controls autoplay muted loop></video>
            </div>
            
            <!-- Image Content -->
            <div id="dashboard-image-content" class="dashboard-main-content">
                <img id="dashboard-image" alt="Dashboard Image">
            </div>
            
            <!-- YouTube Content -->
            <div id="dashboard-youtube-content" class="dashboard-main-content">
                <iframe id="dashboard-youtube-iframe" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>

    <!-- Other Views with Container -->
    <div class="container mx-auto p-4 sm:p-6 lg:p-8">
        <!-- Graph View -->
        <div id="view-graph" class="view">
            <header class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8">
                <div><h1 id="graph-title" class="text-3xl lg:text-4xl font-bold">Real-time Graph</h1></div>
                <div class="flex gap-2 mt-4 sm:mt-0">
                    <button id="clear-graph-data" class="bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">Clear Data</button>
                </div>
            </header>
            
            <div class="bg-gray-900 p-6 rounded-lg shadow-lg">
                <div class="mb-4">
                    <canvas id="main-chart" class="w-full" style="height: 400px;"></canvas>
                </div>
                
                <div id="brush-chart-container" class="mb-4">
                    <canvas id="brush-chart" class="w-full"></canvas>
                </div>
                
                <div id="data-summary" class="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
                    <!-- Summary cards will be generated by JS -->
                </div>
                
                <div class="overflow-x-auto">
                    <table id="data-log" class="w-full text-sm">
                        <thead>
                            <tr>
                                <th class="text-left">Time</th>
                                <!-- Headers will be generated by JS -->
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Data rows will be generated by JS -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Device Status View -->
        <div id="view-status" class="view">
            <header class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8">
                <div>
                    <h1 class="text-3xl lg:text-4xl font-bold">Device Status</h1>
                    <p class="text-gray-400 mt-2">Real-time system monitoring and diagnostics</p>
                </div>
                <div class="flex gap-2 mt-4 sm:mt-0">
                    <button id="app-version-btn" class="bg-gray-600 hover:bg-gray-700 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">v?.?.?</button>
                </div>
            </header>
            
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div class="bg-gray-900 p-6 rounded-lg shadow-lg">
                    <h2 class="text-xl font-semibold mb-4">System Status</h2>
                    <div class="space-y-4">
                        <div class="flex justify-between items-center">
                            <span class="text-gray-400">Connection Status</span>
                            <span id="connection-status" class="text-green-400">Connected</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-gray-400">Data Count</span>
                            <span id="data-count" class="text-white">0</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-gray-400">System Uptime</span>
                            <span id="system-uptime" class="text-white">0s</span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-gray-400">Current Time</span>
                            <span id="status-current-time" class="text-white"></span>
                        </div>
                        <div class="flex justify-between items-center">
                            <span class="text-gray-400">Current Date</span>
                            <span id="status-current-date" class="text-white"></span>
                        </div>
                    </div>
                </div>
                
                <div class="bg-gray-900 p-6 rounded-lg shadow-lg">
                    <h2 class="text-xl font-semibold mb-4">Sensor Readings</h2>
                    <div id="sensor-grid" class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <!-- Sensor cards will be generated by JS -->
                    </div>
                </div>
            </div>
        </div>

        <!-- Settings View -->
        <div id="view-settings" class="view">
            <header class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8">
                <div>
                    <h1 class="text-3xl lg:text-4xl font-bold">Settings</h1>
                    <p class="text-gray-400 mt-2">Configure dashboard parameters and appearance</p>
                </div>
                <div class="flex gap-2 mt-4 sm:mt-0">
                    <button id="change-pin-btn" class="bg-yellow-500 hover:bg-yellow-600 text-black font-medium py-2 px-4 rounded-md transition-colors duration-200">Change PIN</button>
                    <button id="export-settings" class="bg-green-500 hover:bg-green-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">Export Settings</button>
                    <input type="file" id="import-settings" accept=".json" class="hidden">
                    <button id="import-settings-btn" class="bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">Import Settings</button>
                    <button id="save-settings" class="bg-indigo-500 hover:bg-indigo-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">Save Settings</button>
                    <button id="restore-defaults" class="bg-red-500 hover:bg-red-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">Restore Defaults</button>
                </div>
            </header>
            
            <div id="settings-form-container" class="bg-gray-900 p-6 rounded-lg shadow-lg">
                <div class="space-y-6">
                    <!-- Connection & Data Settings -->
                    <div class="pt-6 border-t border-gray-700">
                        <h3 class="flex items-center text-lg font-semibold text-gray-300 mb-4">Connection & Data Settings</h3>
                        <div class="space-y-4">
                            <div>
                                <label for="settings-api-url" class="block text-sm font-medium text-gray-400 mb-2">Data Source URL</label>
                                <input type="url" id="settings-api-url" class="settings-input">
                            </div>
                            <div>
                                <label for="settings-interval" class="block text-sm font-medium text-gray-400 mb-2">Refresh every (seconds)</label>
                                <input type="number" id="settings-interval" min="1" class="settings-input">
                            </div>
                            <div>
                                <label for="settings-retention" class="block text-sm font-medium text-gray-400 mb-2">Data Retention (hours)</label>
                                <input type="number" id="settings-retention" min="1" class="settings-input">
                                <p id="storage-estimate" class="text-xs text-gray-500 mt-1 h-4"></p>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Dashboard Appearance -->
                    <div class="pt-6 border-t border-gray-700">
                        <h3 class="flex items-center text-lg font-semibold text-gray-300 mb-4">Dashboard Appearance</h3>
                        <div class="space-y-4">
                            <div>
                                <label for="settings-header-caption" class="block text-sm font-medium text-gray-400 mb-2">Header Caption</label>
                                <input type="text" id="settings-header-caption" class="settings-input">
                            </div>
                            <div>
                                <label for="settings-header-subcaption" class="block text-sm font-medium text-gray-400 mb-2">Header Sub-caption</label>
                                <input type="text" id="settings-header-subcaption" class="settings-input">
                            </div>
                            
                            <!-- Logo Settings -->
                            <div class="flex items-center">
                                <input id="settings-show-logo" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-logo" class="ml-2 block text-sm font-medium text-gray-400">Show Logo</label>
                            </div>
                            <div id="logo-picker-container"></div>
                            
                            <!-- Header Background Settings -->
                            <div class="flex items-center">
                                <input id="settings-show-header-bg" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-header-bg" class="ml-2 block text-sm font-medium text-gray-400">Show Header Background Image</label>
                            </div>
                            <div id="header-bg-picker-container"></div>
                            <div>
                                <label class="block text-sm font-medium text-gray-400 mb-2">Header Background Color (Fallback)</label>
                                <input type="color" id="settings-header-bg-color" class="settings-input">
                            </div>
                            
                            <!-- Main Background Settings -->
                            <div class="flex items-center">
                                <input id="settings-show-main-bg" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-main-bg" class="ml-2 block text-sm font-medium text-gray-400">Show Main Background Image</label>
                            </div>
                            <div id="main-bg-picker-container"></div>
                            <div>
                                <label class="block text-sm font-medium text-gray-400 mb-2">Main Background Color (Fallback)</label>
                                <input type="color" id="settings-main-bg-color" class="settings-input">
                            </div>
                        </div>
                    </div>
                    
                    <!-- Parameters Configuration -->
                    <div class="pt-6 border-t border-gray-700">
                        <h3 class="flex items-center text-lg font-semibold text-gray-300 mb-4">Parameters Configuration</h3>
                        <div class="space-y-4">
                            <div id="settings-params-container" class="settings-param-container">
                                <!-- Parameters will be generated by JS -->
                            </div>
                            <button id="add-parameter" class="bg-green-500 hover:bg-green-600 text-white font-medium py-2 px-4 rounded-md transition-colors duration-200">+ Add Parameter</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- PIN Modal -->
    <div id="pin-modal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 hidden">
        <div class="bg-white rounded-lg p-8 w-96 max-w-full mx-4">
            <h2 id="pin-modal-title" class="text-2xl font-bold text-gray-900 text-center mb-2">Enter PIN</h2>
            <p id="pin-modal-subtitle" class="text-gray-600 text-center mb-6">Please enter your 6-digit PIN to access settings.</p>
            <div class="w-64 mx-auto mb-4">
                <input type="text" id="pin-input" maxlength="6" class="w-full text-3xl font-bold bg-gray-100 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-indigo-500">
            </div>
            <p id="pin-error" class="text-red-500 text-sm text-center h-5 mb-4"></p>
            <div id="pin-keypad" class="grid grid-cols-3 gap-4">
                <!-- Keypad buttons will be generated by JS -->
            </div>
            <div class="flex justify-center mt-6">
                <button id="cancel-pin-btn" class="px-6 py-2 bg-gray-300 hover:bg-gray-400 text-gray-800 rounded-lg">Cancel</button>
            </div>
        </div>
    </div>

    <!-- Load main application -->
    <script type="module" src="assets/js/app.js"></script>
</body>
</html>