<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Water Quality Dashboard (PHP Version)</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    
    <!-- Link to external CSS file -->
    <link rel="stylesheet" href="assets/style.css">
</head>
<body class="bg-black text-white">
    
    <!-- Main Navigation -->
    <nav class="bg-gray-900 p-4 shadow-lg sticky top-0 z-40">
        <div class="container mx-auto flex justify-center items-center gap-2 sm:gap-4">
            <button data-view="dashboard" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base active">Dashboard</button>
            <button data-view="graph" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Graph</button>
            <button data-view="status" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Device Status</button>
            <button data-view="settings" class="nav-btn px-4 py-2 rounded-lg text-sm sm:text-base">Settings</button>
        </div>
    </nav>

    <!-- ======== Main Content Area ======== -->
    <div class="container mx-auto p-4 sm:p-6 lg:p-8">
        <!-- Dashboard View -->
        <div id="view-dashboard" class="view active dashboard-background">
            <div class="dashboard-overlay"></div>
            <div class="dashboard-content">
                <div id="dashboard-ui-elements">
                    <header id="dashboard-header" class="p-4 mb-4" style="background-size: cover; background-position: center;">
                        <div class="flex items-center gap-4 h-20">
                            <img id="dashboard-logo" src="https://placehold.co/200x200/transparent/white?text=Logo" alt="Logo" class="h-full w-auto object-contain">
                            <div>
                                <h2 id="header-caption" class="text-2xl font-bold text-white"></h2>
                                <p id="header-subcaption" class="text-lg text-gray-300"></p>
                            </div>
                        </div>
                    </header>
                     <div id="operation-mode-container" class="bg-gray-800 bg-opacity-70 p-3 rounded-lg border border-gray-600 flex justify-center items-center gap-6">
                        <h3 class="text-white font-bold">OPERATION MODE</h3>
                        <div id="operation-mode-lights" class="flex gap-4">
                            <!-- Lights will be generated by JS -->
                        </div>
                    </div>
                </div>
                <main class="p-4">
                     <div id="dashboard-graph-content" class="dashboard-main-content active" style="height: 50vh;">
                         <canvas id="dashboardBarChart"></canvas>
                     </div>
                     <div id="dashboard-video-content" class="dashboard-main-content">
                         <video id="dashboard-video" controls autoplay muted loop></video>
                     </div>
                     <div id="dashboard-image-content" class="dashboard-main-content">
                         <img id="dashboard-image" alt="Dashboard Image">
                     </div>
                     <div id="dashboard-youtube-content" class="dashboard-main-content">
                        <iframe id="dashboard-youtube-iframe" class="w-full h-full" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                     </div>
                     <div id="dashboard-values-container" class="flex justify-around mt-2 text-white text-center"></div>
                </main>
            </div>
        </div>

        <!-- Graph View -->
        <div id="view-graph" class="view">
            <header class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8">
                <div><h1 id="graph-title" class="text-3xl lg:text-4xl font-bold">Real-time Graph</h1></div>
                 <button id="reset-zoom-btn" class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg">Reset View</button>
            </header>
            
            <section class="bg-gray-900 p-4 rounded-lg mb-4"><h3 class="text-lg font-semibold mb-3">Select parameters to display:</h3><div id="graph-param-checkboxes" class="flex flex-wrap gap-x-6 gap-y-2"></div></section>
            
            <main class="bg-gray-900 p-4 sm:p-6 rounded-lg">
                <div style="height: 400px;"><canvas id="mainChart"></canvas></div>
                <div id="brush-chart-container" class="mt-4">
                    <canvas id="brushChart"></canvas>
                    <div id="brush">
                        <div class="brush-handle left"></div>
                        <div class="brush-handle right"></div>
                    </div>
                </div>
            </main>
            
            <!-- Statistics Section -->
            <section class="mt-8">
                <h2 class="text-xl font-bold mb-4">Summary (for selected time range)</h2>
                <div id="graph-stats-container" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
                    <!-- Stat cards will be generated by JS -->
                </div>
            </section>

            <!-- Data Table Section -->
            <section class="mt-8">
                <div class="flex justify-between items-center mb-4">
                    <h2 class="text-xl font-bold">Data Log (latest 200 entries)</h2>
                    <button id="export-csv-btn" class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg text-sm">
                        Export as CSV
                    </button>
                </div>
                <div class="bg-gray-900 p-1 rounded-lg overflow-x-auto max-h-96">
                    <table id="history-table" class="w-full text-sm text-left text-gray-400">
                        <thead class="text-xs text-gray-300 uppercase bg-gray-800 sticky top-0">
                            <!-- Table headers will be generated by JS -->
                        </thead>
                        <tbody id="history-table-body">
                            <!-- Table rows will be generated by JS -->
                        </tbody>
                    </table>
                </div>
            </section>
        </div>

        <!-- Device Status View -->
        <div id="view-status" class="view">
            <header class="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8">
                <div><h1 class="text-4xl lg:text-5xl font-bold">System Status</h1></div>
                <div class="text-right mt-4 sm:mt-0">
                    <p id="status-current-time" class="text-2xl lg:text-3xl font-bold"></p>
                    <p id="status-current-date" class="text-base text-gray-300"></p>
                </div>
            </header>
            
            <main class="space-y-8">
                 <!-- System Status Section -->
                <section class="bg-gray-900 p-6 rounded-xl">
                    <h2 class="text-xl font-bold text-yellow-400 mb-4 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2"><path stroke-linecap="round" stroke-linejoin="round" d="M21.75 17.25v-.228a4.5 4.5 0 00-.12-1.03l-2.268-9.64a3.375 3.375 0 00-3.285-2.65H7.923a3.375 3.375 0 00-3.285 2.65l-2.268 9.64a4.5 4.5 0 00-.12 1.03v.228m15.457 0a4.5 4.5 0 01-3.223 3.223h-8.01a4.5 4.5 0 01-3.223-3.223m14.466 0M3.75 17.25h16.5" /></svg>
                        System Overview
                    </h2>
                    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        <div id="system-connection-card" class="status-card bg-gray-800 p-4 rounded-lg">
                            <h3 class="text-gray-400 text-sm">Dashboard Connection</h3>
                            <div id="system-connection-status" class="text-xl font-bold mt-1">Connecting...</div>
                        </div>
                        <div id="api-connection-card" class="status-card bg-gray-800 p-4 rounded-lg">
                            <h3 class="text-gray-400 text-sm">Data Source (API)</h3>
                            <div id="api-connection-status" class="text-xl font-bold mt-1">Checking...</div>
                        </div>
                        <div class="status-card bg-gray-800 p-4 rounded-lg">
                            <h3 class="text-gray-400 text-sm">Last Data Received</h3>
                            <div id="system-last-data-time" class="text-xl font-bold mt-1">N/A</div>
                        </div>
                        <div class="status-card bg-gray-800 p-4 rounded-lg">
                            <h3 class="text-gray-400 text-sm">Data Latency</h3>
                            <div id="system-data-latency" class="text-xl font-bold mt-1">N/A</div>
                        </div>
                    </div>
                </section>
                
                <!-- Sensor Status Section -->
                <section class="bg-gray-900 p-6 rounded-xl">
                    <h2 class="text-xl font-bold text-yellow-400 mb-4 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M12 6V3m0 18v-3m6-6h3m-3 6h3m-9-9a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V9a2 2 0 00-2-2h-2zm0 0V3m0 6V3m0 0a2 2 0 00-2 2v2" /></svg>
                        Sensor Status
                    </h2>
                    <div id="sensor-status-grid" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                        <!-- Rich sensor cards will be generated by JS -->
                    </div>
                </section>

                <!-- Status Log Section -->
                <section class="bg-gray-900 p-6 rounded-xl">
                    <h2 class="text-xl font-bold text-yellow-400 mb-4 flex items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5" /></svg>
                        Status Event Log
                    </h2>
                     <div class="bg-gray-800 rounded-lg overflow-hidden max-h-60 overflow-y-auto">
                        <table class="w-full text-sm text-left">
                            <tbody id="status-log-body">
                                <!-- Log entries will be generated by JS -->
                            </tbody>
                        </table>
                    </div>
                </section>
            </main>
        </div>

        <!-- Settings View -->
        <div id="view-settings" class="view">
             <div class="w-full max-w-3xl mx-auto bg-gray-100 text-gray-800 rounded-xl shadow-lg p-8 relative" id="settings-form-container">
                <button id="app-version-btn" class="absolute top-4 right-4 text-xs text-gray-400 hover:text-gray-600 underline focus:outline-none"></button>
                <div class="text-center"><h1 class="text-2xl font-bold mb-2">Display Settings</h1><p class="text-gray-500 mb-8">Configure connection, parameters, and display options</p></div>
                
                <div id="localStorage-warning" class="hidden p-4 mb-4 text-sm text-yellow-800 rounded-lg bg-yellow-50" role="alert">
                    <span class="font-medium">Browser storage is unavailable!</span> Settings will be temporary and will be lost when this tab is closed.
                </div>

                <div class="space-y-6">
                    <!-- Connection & Data Settings -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Connection & Data Settings<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">- Data Source URL: The web address (API endpoint) where the dashboard fetches its data.<br>- Refresh every: How often (in seconds) the dashboard should request new data.<br>- Data Retention: How long (in hours) historical data for the line graph should be stored in the browser.</span></span></h3>
                        <div class="space-y-4">
                            <div><label for="settings-api-url" class="block text-sm font-medium mb-2">Data Source URL</label><input type="url" id="settings-api-url" class="settings-input"></div>
                            <div><label for="settings-interval" class="block text-sm font-medium mb-2">Refresh every (seconds)</label><input type="number" id="settings-interval" min="1" class="settings-input"></div>
                            <div>
                                <label for="settings-retention" class="block text-sm font-medium mb-2">Data Retention (hours)</label>
                                <input type="number" id="settings-retention" min="1" class="settings-input">
                                <p id="storage-estimate" class="text-xs text-gray-500 mt-1 h-4"></p>
                            </div>
                        </div>
                    </div>
                     <!-- Dashboard Appearance -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Dashboard Appearance<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">Customize the visual elements of the dashboard header and backgrounds. You can toggle the visibility of each image.</span></span></h3>
                        <div class="space-y-6">
                            <!-- Header Text -->
                            <div>
                                <label for="settings-header-caption" class="block text-sm font-medium mb-2">Header Caption</label>
                                <input type="text" id="settings-header-caption" class="settings-input">
                            </div>
                            <div>
                                <label for="settings-header-caption-fontsize" class="block text-sm font-medium mb-2">Header Caption Font Size (px)</label>
                                <input type="number" id="settings-header-caption-fontsize" class="settings-input">
                            </div>
                            <div>
                                <label for="settings-header-subcaption" class="block text-sm font-medium mb-2">Header Sub-caption</label>
                                <input type="text" id="settings-header-subcaption" class="settings-input">
                            </div>
                             <div>
                                <label for="settings-header-subcaption-fontsize" class="block text-sm font-medium mb-2">Header Sub-caption Font Size (px)</label>
                                <input type="number" id="settings-header-subcaption-fontsize" class="settings-input">
                            </div>

                            <div class="pt-4 border-t"></div>

                             <!-- Logo Settings -->
                            <div class="flex items-center">
                                <input id="settings-show-logo" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-logo" class="ml-2 block text-sm font-medium">Show Logo</label>
                            </div>
                            <div id="logo-picker-container"></div>
                            <p class="text-xs text-gray-500 mt-1">แนะนำ: 200x200px (ภาพจะถูกปรับขนาดให้พอดี)</p>

                            <div class="pt-4 border-t"></div>

                            <!-- Header Background Settings -->
                            <div class="flex items-center">
                                <input id="settings-show-header-bg" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-header-bg" class="ml-2 block text-sm font-medium">Show Header Background Image</label>
                            </div>
                            <div id="header-bg-picker-container"></div>
                            <p class="text-xs text-gray-500 mt-1">แนะนำ: 1920x200px (แนวนอนกว้าง)</p>
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Header Background Color (Fallback)</label>
                                <input type="color" id="settings-header-bg-color">
                            </div>

                            <div class="pt-4 border-t"></div>

                            <!-- Main Background Settings -->
                             <div class="flex items-center">
                                <input id="settings-show-main-bg" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-show-main-bg" class="ml-2 block text-sm font-medium">Show Main Background Image</label>
                            </div>
                            <div id="main-bg-picker-container"></div>
                            <p class="text-xs text-gray-500 mt-1">แนะนำ: 1920x1080px (สัดส่วน 16:9)</p>
                             <div>
                                <label class="block text-sm font-medium text-gray-700 mb-2">Main Background Color (Fallback)</label>
                                <input type="color" id="settings-main-bg-color">
                            </div>
                        </div>
                    </div>
                     <!-- Dashboard Content Rotation -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Dashboard Content Rotation<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">Automatically rotate between graph, video, and image on the dashboard.<br>- Enable/disable the rotation.<br>- Drag to reorder.<br>- Set duration for each view.<br>- Set sources for video and image.</span></span></h3>
                        <div class="space-y-4">
                            <div class="flex items-center">
                                <input id="settings-rotation-enabled" type="checkbox" class="h-4 w-4 rounded">
                                <label for="settings-rotation-enabled" class="ml-2 block text-sm font-medium">Enable Content Rotation</label>
                            </div>
                             <div id="settings-rotation-list" class="space-y-3">
                                <!-- Rotation items will be generated here -->
                            </div>
                            <div id="add-slide-buttons" class="flex gap-2">
                                <button data-type="graph" class="add-slide-btn text-sm bg-blue-500 text-white px-3 py-1 rounded-md hover:bg-blue-600">+ Graph</button>
                                <button data-type="video" class="add-slide-btn text-sm bg-blue-500 text-white px-3 py-1 rounded-md hover:bg-blue-600">+ Video</button>
                                <button data-type="image" class="add-slide-btn text-sm bg-blue-500 text-white px-3 py-1 rounded-md hover:bg-blue-600">+ Image</button>
                            </div>
                        </div>
                    </div>
                     <!-- Dashboard Bar Chart Styling -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Dashboard Bar Chart Styling<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">Fine-tune the colors and font sizes for all elements in the main dashboard bar chart.</span></span></h3>
                        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <div><label class="block text-sm font-medium mb-2">Bar Color</label><input type="color" id="settings-bar-color"></div>
                            <div><label class="block text-sm font-medium mb-2">Range Text Color</label><input type="color" id="settings-bar-range-text-color"></div>
                            <div><label class="block text-sm font-medium mb-2">Label Text Color</label><input type="color" id="settings-bar-label-text-color"></div>
                            <div><label class="block text-sm font-medium mb-2">Value Text Color</label><input type="color" id="settings-bar-value-text-color"></div>
                            <div><label class="block text-sm font-medium mb-2">Unit Text Color</label><input type="color" id="settings-bar-unit-text-color"></div>
                        </div>
                         <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                            <div><label class="block text-sm font-medium mb-2">Range Font Size (px)</label><input type="number" id="settings-bar-range-font-size" class="settings-input"></div>
                             <div><label class="block text-sm font-medium mb-2">Label Font Size (px)</label><input type="number" id="settings-bar-label-font-size" class="settings-input"></div>
                            <div><label class="block text-sm font-medium mb-2">Value Font Size (px)</label><input type="number" id="settings-bar-value-font-size" class="settings-input"></div>
                            <div><label class="block text-sm font-medium mb-2">Unit Font Size (px)</label><input type="number" id="settings-bar-unit-font-size" class="settings-input"></div>
                        </div>
                    </div>
                     <!-- Operation Mode Settings -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Operation Mode Settings<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">- Mode Status JSON Key: The name of the variable in your data source that indicates the current operation mode.<br>- Mode Values: Define the exact value from your data that corresponds to each mode name. This links the data to the status lights on the dashboard.</span></span></h3>
                        <div class="space-y-4">
                            <div><label for="settings-mode-key" class="block text-sm font-medium mb-2">Mode Status JSON Key</label><input type="text" id="settings-mode-key" class="settings-input"></div>
                             <p class="text-sm text-gray-600">Define the value for each mode that triggers the light.</p>
                             <div id="settings-mode-values" class="space-y-2">
                                <!-- Mode value inputs will be generated here -->
                             </div>
                        </div>
                    </div>
                     <!-- Proxy Settings -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Proxy Settings (Managed by Server)<span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">Proxy is now handled by the PHP backend. All data requests from this dashboard are automatically routed through the server to prevent CORS issues. There are no client-side proxy settings to configure.</span></span></h3><div class="space-y-4"><div class="flex items-center p-3 bg-indigo-100 text-indigo-800 rounded-lg"><svg class="w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg><p>Proxy is enabled and managed by the server.</p></div></div></div>
                     <!-- Test & Refresh -->
                    <div class="pt-6 border-t"><h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">Test & Refresh <span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">- Test: Fetches data from the URL to check if the connection is working and displays the raw response.<br>- Refresh: Immediately fetches new data and updates the entire dashboard, without waiting for the next refresh interval.</span></span></h3><div class="flex gap-4"><button id="settings-test-connection-btn" class="w-1/2 px-4 py-2 bg-indigo-600 text-white font-semibold rounded-lg">Test</button><button id="settings-refresh-data-btn" class="w-1/2 px-4 py-2 bg-green-600 text-white font-semibold rounded-lg">Refresh</button></div><div class="mt-2"><pre id="settings-raw-result" class="bg-gray-800 text-white p-2 rounded-md text-xs whitespace-pre-wrap break-all h-24 overflow-y-auto"></pre></div></div>
                    
                    <!-- PIN Management -->
                    <div class="pt-6 border-t">
                        <h3 class="flex items-center text-lg font-semibold text-gray-700 mb-4">PIN Management
                            <span class="tooltip-trigger">
                                <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                <span class="tooltip-content">
                                    - <b>Change PIN:</b> Allows you to change your current 6-digit PIN after verifying the old one.
                                </span>
                            </span>
                        </h3>
                        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                            <button id="settings-change-pin-btn" class="w-full px-4 py-3 bg-yellow-600 text-white font-semibold rounded-lg shadow-md hover:bg-yellow-700 text-sm">Change PIN</button>
                        </div>
                    </div>

                     <!-- Parameter Settings -->
                    <div class="pt-6 border-t"><div class="flex justify-between items-center mb-4"><h3 class="flex items-center text-lg font-semibold text-gray-700">Parameter Settings <span class="tooltip-trigger"><svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg><span class="tooltip-content">- Key: The exact variable name from the data source (JSON).<br>- Formula: A mathematical expression to convert the raw value. Use 'x' as the variable (e.g., x * 0.01).<br>- Min/Max Value: Sets the 0-100% range for the bar graph on the dashboard.<br>- Display Max: Caps the numerical value shown on the dashboard (does not affect the graph page).<br>- Type: 'Value' is for numerical data. 'Status' is for text-based data.<br>- Mode: 'Real' uses the data source URL. 'Simulated' generates random test data.</span></span></h3><button id="settings-add-param-btn" class="text-sm bg-green-500 text-white px-3 py-1 rounded-md hover:bg-green-600">+</button></div><div id="settings-parameter-list" class="space-y-3"></div></div>
                </div>

                <div class="settings-footer">
                    <div class="space-y-4">
                        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                             <button id="settings-save-btn" class="w-full px-4 py-3 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 text-sm">Save and Apply</button>
                             <button id="settings-import-btn" class="w-full px-4 py-3 bg-green-600 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 text-sm">Import from File</button>
                             <button id="settings-export-btn" class="w-full px-4 py-3 bg-indigo-600 text-white font-semibold rounded-lg shadow-md hover:bg-indigo-700 text-sm">Export to File</button>
                             <button id="settings-restore-btn" class="w-full px-4 py-3 bg-red-600 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 text-sm">Restore Defaults</button>
                        </div>
                        <p id="settings-feedback" class="text-green-600 text-sm mt-2 h-5 text-center"></p>
                    </div>
                </div>
                <form id="import-form" class="hidden">
                    <input type="file" id="settings-import-file-input" name="settings-import-file-input" accept=".json">
                </form>
             </div>
        </div>
    </div>
    
    <!-- Modals -->
    <div id="unsaved-changes-modal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 hidden">
        <div class="bg-white text-gray-800 p-8 rounded-lg shadow-xl max-w-sm w-full">
            <h3 class="text-xl font-bold mb-4">Unsaved Changes</h3>
            <p class="mb-6">You have unsaved changes. Are you sure you want to leave this page?</p>
            <div class="flex justify-end gap-4">
                <button id="cancel-leave-btn" class="px-4 py-2 bg-gray-300 rounded-lg">Cancel</button>
                <button id="confirm-leave-btn" class="px-4 py-2 bg-red-600 text-white rounded-lg">Leave Page</button>
            </div>
        </div>
    </div>

    <div id="restore-defaults-modal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 hidden">
        <div class="bg-white text-gray-800 p-8 rounded-lg shadow-xl max-w-sm w-full">
            <h3 class="text-xl font-bold mb-4">Restore Default Settings?</h3>
            <p class="mb-6">Are you sure? This will remove all your current settings and restore the original defaults. This action cannot be undone.</p>
            <div class="flex justify-end gap-4">
                <button id="cancel-restore-btn" class="px-4 py-2 bg-gray-300 rounded-lg">Cancel</button>
                <button id="confirm-restore-btn" class="px-4 py-2 bg-red-600 text-white rounded-lg">Restore Defaults</button>
            </div>
        </div>
    </div>

    <div id="changelog-modal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 hidden">
        <div class="bg-white text-gray-800 p-6 rounded-lg shadow-xl max-w-md w-full m-4">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold">Changelog</h3>
                <button id="close-changelog-btn" class="text-2xl font-bold text-gray-500 hover:text-gray-800">&times;</button>
            </div>
            <div id="changelog-content" class="space-y-4 text-sm max-h-80 overflow-y-auto pr-2">
                <!-- Content is generated dynamically -->
            </div>
            <div class="mt-6 text-center text-xs">
                <a href="https://ilustro.co" target="_blank" rel="noopener noreferrer" class="text-indigo-600 hover:underline">
                    Powered by Ilustro.co
                </a>
            </div>
        </div>
    </div>
    
    <div id="pin-modal" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 hidden">
        <div class="bg-white text-gray-800 p-8 rounded-lg shadow-xl max-w-sm w-full">
            <h3 id="pin-modal-title" class="text-xl font-bold mb-2 text-center">Enter PIN</h3>
            <p id="pin-modal-subtitle" class="text-gray-600 mb-6 text-center">Please enter your 6-digit PIN to access settings.</p>
            <div class="w-64 mx-auto mb-4">
                <input type="text" id="pin-input" maxlength="6" class="w-full text-3xl font-bold bg-gray-100 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-indigo-500">
            </div>
            <p id="pin-error" class="text-red-500 text-sm text-center h-5 mb-4"></p>
            <div id="pin-keypad" class="grid grid-cols-3 gap-4">
                <!-- Keypad buttons will be generated by JS -->
            </div>
             <div class="flex justify-center mt-6">
                <button id="cancel-pin-btn" class="px-6 py-2 bg-gray-300 hover:bg-gray-400 text-gray-800 rounded-lg">Cancel</button>
            </div>
        </div>
    </div>

    <!-- Templates -->
    <template id="settings-param-row-template">
        <div class="parameter-row p-4 border rounded-lg bg-white shadow-sm relative space-y-4" draggable="true">
            <div class="drag-handle" title="Drag to reorder">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
                  <path d="M7 2a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM7 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-4 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-4 4a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                </svg>
            </div>
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4 items-end">
                <!-- Basic Info -->
                <div>
                    <label class="block text-xs font-medium text-gray-500">Display Name</label>
                    <input type="text" class="param-displayName settings-input mt-1 w-full">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Key</label>
                    <input type="text" class="param-jsonKey settings-input mt-1 w-full">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Unit</label>
                    <input type="text" class="param-unit settings-input mt-1 w-full">
                </div>
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Formula (use 'x')</label>
                    <input type="text" class="param-formula settings-input mt-1 w-full" placeholder="e.g., x * 0.01">
                </div>
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Icon (SVG)</label>
                    <input type="text" class="param-icon settings-input mt-1 w-full" placeholder="<svg>...</svg>">
                </div>
            </div>
             <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-4 border-t mt-4">
                <!-- Live Values -->
                <div>
                    <label class="block text-xs font-medium text-gray-500">Range Text (Auto)</label>
                    <input type="text" class="param-rangeText settings-input mt-1 w-full bg-gray-200" readonly>
                </div>
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Raw Value (Live)</label>
                    <input type="text" class="param-rawValue settings-input mt-1 w-full bg-gray-200" readonly>
                </div>
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Calculated Value (Live)</label>
                    <input type="text" class="param-calculatedValue settings-input mt-1 w-full bg-gray-200" readonly>
                </div>
            </div>
            <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t mt-4">
                <!-- Thresholds -->
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Critical Low</label>
                    <input type="number" step="any" class="param-criticalLow settings-input mt-1 w-full" placeholder="e.g. 0">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Warning Low</label>
                    <input type="number" step="any" class="param-warningLow settings-input mt-1 w-full" placeholder="e.g. 10">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Warning High</label>
                    <input type="number" step="any" class="param-warningHigh settings-input mt-1 w-full" placeholder="e.g. 90">
                </div>
                 <div>
                    <label class="block text-xs font-medium text-gray-500">Critical High</label>
                    <input type="number" step="any" class="param-criticalHigh settings-input mt-1 w-full" placeholder="e.g. 100">
                </div>
            </div>
            <div class="sim-settings hidden pt-4 border-t grid grid-cols-2 md:grid-cols-4 gap-4 items-end">
                 <!-- Simulation -->
                 <div>
                     <label class="block text-xs font-medium text-gray-500">Sim. Initial</label>
                     <input type="number" step="0.01" class="param-sim-initial settings-input w-full mt-1">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Sim. Range (+/-)</label>
                    <input type="number" step="0.01" class="param-sim-range settings-input w-full mt-1">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Sim. Min</label>
                    <input type="number" step="0.01" class="param-sim-min settings-input w-full mt-1">
                </div>
                <div>
                    <label class="block text-xs font-medium text-gray-500">Sim. Max</label>
                    <input type="number" step="0.01" class="param-sim-max settings-input w-full mt-1">
                </div>
            </div>
            <button class="remove-param-btn bg-red-500 text-white rounded-full h-6 w-6 flex items-center justify-center absolute -top-3 -right-3 text-sm font-bold shadow-lg">-</button>
        </div>
    </template>
    
    <script type="module" src="assets/js/app.js"></script>

</body>
</html>
